# Generated by Django 4.2.1 on 2023-06-04 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['date_created'], 'verbose_name_plural': 'blogs'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['date_created'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
