# Generated by Django 4.2.1 on 2023-06-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_blog_options_alter_category_options_blog_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'blogs'},
        ),
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
    ]
